import { REGEX_READ_ALIASES } from "../../constants";
import { StatEffect } from "../../types";
import getEmitters from "../../utils/emitHelper";
import { captureFrom } from "../../utils/makeMatcher";
import { HandlerOptions } from "../server";
import items, { Item, ItemIds } from "./items";

export type DurableAugmentationOpts = {
  quest?: boolean;
  statEffects?: StatEffect[];
};

export function augment_durable (item: Item, augmentation: DurableAugmentationOpts): Item {
  if (augmentation.quest !== undefined) item.quest = augmentation.quest;
  if (augmentation.statEffects !== undefined) item.statEffects = augmentation.statEffects;
  return item;
}

export function augment_book (item: Item): Item {
  item.handleItemCommand = (handlerOptions: HandlerOptions): boolean => {
    const { character, command, socket } = handlerOptions;
    const { name } = character;
    const { emitOthers, emitSelf } = getEmitters(socket, character.scene_id);
    
    const readMatch: string | null = captureFrom(command, REGEX_READ_ALIASES);
    if (readMatch !== null) {
      if (item.keywords.includes(readMatch)) {
        const actorText: string[] = [];
        actorText.push(`You open a copy of ${item.title}, skipping to the good bits...`);

        switch (item.id) {
          case ItemIds.FILSTREDS_GUIDE_BOOK:
            actorText.push(`As you open the cover and turn the pages of this book, you get two strange sensations at the same time.  One makes you feel a bit as if you are being watched.  The other gives the near-nauseating feeling that it is the world that is turning around the pages.  You are shocked to find your own name printed on the pages.`);
            actorText.push(`"Welcome, ${name}, to your life on the continent!  During your stay here, you may find it useful to have a guide to some of the many wonderful things you can get up to here.  Allow me to take you by the hand and show you some of the best."`);
            actorText.push(`"In this world, you will find that you are free to use your own words to make your way through life.  You will find suggestions highlighted throughout your journey, hinting that you may be able to [go here], [eat this],  or [fight that].  You can try these words as presented, but don't hesitate to try some other things.  You never know what might make your life a little easier, or might surprise you!  But along the same lines, be careful, and be specific!  If you are carrying a glorious steel longsword and a cheap tin rapier, and you simply say [drop sword], there's no telling which you'll let go of!  Now, onto some particulars."`);
            actorText.push(`"In this world, one of the most basic things you can do is [look] at something.  If you just [look] without specifying what you want to look at, you will end up looking at your surroundings, which is quite useful on its own.  But you can also [inspect {something}] if you want to learn more about it.  This goes for items in your environment, in your [inventory], or worn on your[self]."`);
            actorText.push(`"In this world, you can [go] places.  When you [look] at your surroundings, you will find clues as to where you can [go] from where you are.  For example, if you are standing at a crossroads and see the path stretching away toward the rising sun, you can [go east]."`);
            actorText.push(`"In this world, you can [buy] things.  Naturally, you can only buy them from people who are selling them.  Find these people, [talk] to them to learn what they are selling, and [purchase] to your heart's content!  Oh, you'll need to have the requisite funds at hand, of course.  You can check on this by perusing your [inventory].  This will also allow you to see what else you are carrying."`);
            actorText.push(`"In this world, you can [eat] things, [drink] things, and more generally, [use] things.  As you find things throughout the world, you can try to eat, drink, or use them.  Your mileage may vary when going off the rails.  I won't accept any responsibility for folks trying to eat decorative shields in the park."`);
            actorText.push(`"In this world, you will find items in the scenes you visit.  You can [get] these items to add them to your inventory.  You can only carry so much, so be careful about picking up every other thing you come across.  If you find that you are carrying too much, you can review what you are carrying by checking your [inventory], and you are free to [drop] anything you are carrying."`);
            actorText.push(`"In this world, you will find various pieces of armor, weaponry, clothing, and other items that you can [equip] or [wear].  Each of these items fits a particular part of your body.  I'm not accountable if you try to wear pants on your head, or a hat on your ... anything else, really.  If you decide you want to equip something else, you can just [equip] it and it will automatically replace what you were already wearing (returning the old item to your inventory), or if you want to wear nothing, for whatever reason, you can [remove] an item."`);
            actorText.push(`"In this world, if you want to know what things you already have equipped, or learn more about your current status, you can look at your[self].  You can learn a lot about your[self], by taking a good look at your[self]."`);
            actorText.push(`"In this world, you may want to grow your [skills] and [abilities].  You can review your [skills] and [abilities], of course, and you can also, separately, improve their [level].  By checking on the [level] of energy you've gathered from the Lifelight, you can see how much you need to improve any of your skills or abilities."`);
            actorText.push(`"In this world, you might come across people or creatures you don't like very much.  In fact, you might come across some that you dislike enough that you want to end their lives, for what I can only imagine would be perfectly legal and justifiable reasons.  In this case, you can [fight] them.  But be careful with this, because if you lose, the Lifelight will send you back to the last place you took a [rest]."`);
            actorText.push(`"In this world, your health can suffer if you take on too many injuries from your various fights and adventures.  If you need to, you can find places to [sleep].  These will usually have beds or other indications that there are good accommodations for taking a [rest].  Having a [rest] will restore your health."`);
            actorText.push(`"In this world, you might obtain items that you want to [give] to someone.  For example, someone might give you something in the hopes you'll be their courier.  This is one of the most complicated things you can do in this world, since you have to [give {items} to ~someone~]."`);
            actorText.push(`"In this world, you may find yourself in companionship with a four-legged friend, a pack animal that can help carrying things for you.  In this case, you can [give {items} to ~them~].  Be careful, as your horse can only carry a limited amount, dictated by the quality of saddlebags they are carrying.  If you want to retrieve something from your horse, you can [get {items} from ~them~].  You can do a lot with your horse - give your horse a [look] to learn more about them.  Beware, your horse will not follow you some places, such as indoors, so make sure you manage your inventory while you are together."`);
            actorText.push(`"In this world, you may end up with jobs to do or [quests] to go on.  If you need to refresh your memory, you can always stop and think about what [missions] you have chosen to undertake, and what [stories] you are involved in."`);
            actorText.push(`"In this world, you will encounter books, scrolls, notes, and other written works.  However, if you are already here, I trust you to know how to [read] something."  The book almost seems to wink at you, somehow.`);
            actorText.push(`"In this world, you'll most likely encounter people or creatures you'd like to learn from or interact with, other than to kill them.  You can [speak] with them to see if they'll talk back.  They may not, but some will."`);
            actorText.push(`"That should be enough to get you started.  May the Lifelight illuminate your path and warm your weary bones!"`);
            break;
          case ItemIds.IMPERIAL_GUIDE_BOOK:
            actorText.push(`"Your survival in the field will necessitate a clear understanding of your surroundings, your situation, and yourself.  How you observe and interpret your situation will directly correlate to your ability to thrive in and respond to that situation.  Thus, this manual prescribes a method of interpretation by which you can better evaluate any given situation and be able to expect superior results from your actions on it."`);
            actorText.push(`"When you observe things, it goes without saying that you would like as much information about those things as possible.  This will allow you to make the best possible decisions about how to interact with those things.  However, not all things can be reduced to simple, comparable numbers.  Sometimes, you must appreciate the context in which you are observing a thing to best understand it."`);
            actorText.push(`"An easy example of this is your weapon's effectiveness.  When you strike an enemy with your weapon, that enemy's reaction might differ from that of another enemy.  This is despite the fact that you are using the same weapon, and may have inflicted the same amount of injury.  We can attribute this difference to the context.  Enduring the same sort of sword wound, for example, a dog can reasonably be expected to react differently than a bear.  And so, when you see a dog behave as if he is on the edge of death at the slash of your blade, do not expect a bear to behave the same."`);
            actorText.push(`"Likewise, when you receive wounds of your own, or undergod the healing process, you will find the same phenomenon taking place.  As a recruit with a weak constitution, you may find the healing properties of a rejuvenative potion to be overwhelmingly refreshing.  As a hardened veteran with more scars, you may be able to endure more punishment, but this means the same healing draft will also restore less of your total bodily condition."`);
            actorText.push(`"Be wary of your context, and how these effects on you and your situation change over time."`);
            actorText.push(`The book continues with specifics of technique and wilderness survival that your are relieved to discover you are already familiar with.`);
            break;
          case ItemIds.PERSONAL_GROWTH_BOOK:
            actorText.push(`"Your relationship with the Lifelight is one of reverence, yes, but also one of eternal personal growth and development.  The Lifelight wants to shine on you, yes, and in so doing, better you, foster your journey with its warmth and energy.  Have you ever wondered how to make the most of this relationship?"`);
            actorText.push(`"You are a being, blessed, yes, with the Lifelight, and thus, capable of doing many things, so many things.  But how can you determine what you are best at?  You may want to [evaluate skills] that are relevant to your job, your health, or your relationships.  By keeping an eye on your [skills], you can maintain awareness of what sort of progress you have made in sharpening each of them.  Never forget, no, that you are better off comparing yourself with only yourself, and where you want yourself to be in your own future, rather than comparing yourself with others, or trying to quantify your skills.  What folly!"`);
            actorText.push(`"Over time, as you work on your skills and on yourself, the Lifelight will bless you with gifts of its warmth and its energy.  Your body will carry this energy with it, yes, and over time accumulate it in greater amounts.  You will feel it in your living flesh, yes, its [level] will rise within you!  As your journey through life progresses, you will find that you can channel this energy into the growth of your skills.  Pray that the Lifelight might lift the [level] of your skills and abilities to the level needed to meet your purpose!"`);
            break
          case ItemIds.REALM_GUIDE_BOOK:
            actorText.push(`"The peoples of this land are divided into realms - or, more colloquially, nations.  These nations and their relationships form the foundation upon which the game of contemporary politics is played.  Over time, borders and relationships - and, it can surely be said, even peoples - doubtless can and do change.  Yesterday, they were one way; tomorrow, they will be another; but today's reader, and perhaps a future reader interested in a contemporary take, will want to know more about the way things stand in the moment, and thus this work is born."`);
            actorText.push(`"May we begin in the north, with the Empire of the Sky.  As its name suggests, it is an empire, a military entity at its core, interested in the governance of its constituent entities of state, be they cities, duchies, nations, or what have you.  While these possess limited local authority to proceed with life as they see fit, the constant presence of imperial military personnel are a close reminder that heavy taxes loom with every harvest and that military service will be expected of the men - and, you may be surprised to know, the women - of every village, however small.  After all, the Empire's second interest is, to the surprise of none, expansion.  It may go without saying that a military machine capable of both expansion and the maintenance of a large, existing empire requires tremendous resources.  By way of simple geography, the Empire of the Sky spans the width of the entire continent - the only realm to do so - though only between the mountains in the far north and the inland sea."`);
            actorText.push(`"To the east of the inland sea, nestled between it and the mountains to the east, and spreading south around the shores of said inland sea, lies the kingdom realm of Thayzhul.  Here live the Weavers, most famous of her denizens, though not her only ones.  Here, magic is fostered, and a strict sense of morality and justice - a code, if you will.  It is, of course, no one's code but theirs, however; and the desires of others may or may not factor into it where politics are concerned.  While there has been much conflict and infighting among the royal family over the years, none argue that Thayzhul has done more than any other realm to keep the wild things of the uncivilized lands to the far east and south at bay, keeping the civilized realms safe from invasion - unless it is by each other.  Thayzhul is known in its own northern reaches for defending the local folk from the Empire of the Sky by way of intimidation if not by brute force, though in some eyes, the kingdom's methods make it no better than an eastern imperial equivalent."`);
            actorText.push(`"At last, we have the so-called Five Realms of the Drear in the west.  To be precise, this name is in some ways inaccurate - as discussed at greater length in my wonderful companion text, '${items.get(ItemIds.THE_FIVE_REALMS_BOOK).title}.  In short, however, we can say that Thayzhul and the Empire of the Sky both regard the Five Realms as one, which they both consider to be inferior, both to themselves and each other.  This is true, doubtless, in terms of size and population.  Only if the Five Realms are taken as a whole would they be on par with the two largest realms.  However, the Five Realms are fractured and distracted by hyperlocal interests.  This, on top of the fact that none of the Five Realms places emphasis, as a cultural or national whole, on either military prowess or magical development, is how the greater region earned the nickname 'The Drear', given by others but adopted within."`);
            actorText.push(`The book begins a much deeper dive into the contemporary politics, geography, economics, religions, and other aspects of the realms.`);
            break;
          case ItemIds.THE_FIVE_REALMS_BOOK:
            actorText.push(`"The name given to the western realms, as a group, is The Five Realms of the Drear.  The name comes from two important facts.  Firstly, there are five realms.  Secondly, the folk who live in them are mere humans and possess no special magical abilities or traits.  While this is considered common knowledge among the people of these realms - and beyond - academics consider it both a casual, and an incorrect, name for the region, for two main reasons.  For one, the people of these realms are not, in fact, forbidden or unable to use magic.  Take, for example, the nation of Ixpanne, famous for its long line of wizards and magical research.  And this being the case, we must thusly include the two other realms in which humans live and may or may not use magic: the Empire of the Sky and Thayzhul.  This would total seven, not five, and no longer be much of a 'Drear', but the two contesting realms take umbrage at the notion, and so we must digress.  For the sake of this text, let us assume there are Five Realms of the Drear"`);
            actorText.push(`"In the northwest, we find the nation of Rocksteppe.  Barren, desolate, and remote, the realm engages in few conflicts and comes under little scrutiny.  It produces few exports, and consumes little, the scant few people who live there subsisting on their flocks, and the sparse pastures on which they graze.  The soil is rocky and sandy, the bedrock shallow, and farming is difficult.  The origin of the name of the nation, you can then surely deduce.  The land is rich not for mineral, nor plant, nor animal, and there is little there to warrant military interest, and so the nation has escaped turmoil for much of its history."`);
            actorText.push(`"To the northeast lies Florenza, a capital and beneficiary of trade.  Its merchants have grown wealthy by fostering a peaceable relationship between the so-called Five Realms, and the Empire of the Sky to the more distant northeast.  While relations between the Five Realms and the Empire continue to deteriorate (see my fabulous companion text, '${items.get(ItemIds.REALM_GUIDE_BOOK).title}'), trade must persist so that civilization may continue to flourish, and Florenza has capitalized on this effect to fabulous, opulent success.  It is, though, Florenza that would be next in line for domination if the Empire were to continue its expansion westward, which quietly troubles many in the region."`);
            actorText.push(`"Most centrally located among the Five Realms is Ixpanne.  Billing itself as the Jewel of the West, this realm appears on the surface to be the most successful.  Beneath the surface, however, the truth of the matter lies in the fact that the nation's leadership commands her course by way of fear.  That applies both to the citizenry - kept in line by a notorious retinue of authoritarian peacekeepers - and Ixpanne's neighbors, who play nicely only for fear of the mighty wizards who reside at Parliament, the capital.  Ixpanne has, by way of this fear, manipulated its surrounding nations to buffer it against threats that might have come from outside the Five Realms.  Ixpanne's one weakness, if it can be said to have one, is that it is the only among the modern realms to be well and truly landlocked."`);
            actorText.push(`"To the southwest rests the realm of Ironhenge.  The land along this western reach of the continent is rich in iron - for which the nation is named - the region is also unusually rich in many other precious and semi-precious minerals.  Thus, while Florenza gathers wealth through trade, and Ixpanne commands success and wealth through fear and political domination, Ironhenge can produce its own wealth right out of the earth.  Excellent works are produced there, and the nation is a manufacturing center like none other.  Apropos of nothing, the nation developed, some decades ago, what is now considered the first and most successful organized espionage corps and training program of any nation.  It is to their chagrin that anyone knows this, though it is an open secret that they continue to set the standard in this domain."`);
            actorText.push(`"Finally, in the southeast, we come to Greenwood, whose name should need no explanation.  Abutting the western border of Thayzhul - called the Threadbare - this nation is an unsurprising blend of the nations that neighbor it.  Trade is heavy, as Greenwood shares borders with Florenza, Ixpanne, Ironhenge, and Thayzhul.  Aspects of magic, while culturally anathema, are nevertheless present due to proximity with Thayzhul and Ixpanne.  With Ironhenge so near to the west, spycraft and suspicion run rampant.  Despite being such a hub among nations, the distinction is unwanted by Greenwood, and she strices for an isolationist policy - with, as you may imagine, mixed results at best."`);
            break;
        }
        emitOthers(`${name} opens a copy of ${item.title} and starts reading.`);
        emitSelf(actorText);
        return true;
      }
    }
  };

  return item;
}

